#
# file:    Makefile
#
CFLAGS = -g

# $@ refers to the pattern *target* (i.e. 'test1')
# $^ refers to all prerequisites (i.e. 'test1.o qthread.o ...')
test1: test1.o qthread.o stack.o switch.o

server: server.o qthread.o stack.o switch.o
